import { Download, FileUp, Moon, PanelTop, Printer, Settings2, Sparkles, Sun } from 'lucide-react'
import { useState } from 'react'
import { create } from 'zustand'

const rooms = ['Workshop','Laundry room','Kitchen','Bedroom','Bachelor','Bathroom','Office','Gym','Sauna','Staircase','Living room','Dining room','Garage','Terrace','Outside','Utility']
const floors = ['BSM','1ST','MEZ','OUT','MEC']
const dots = { BSM:'#3b82f6', '1ST':'#16a36a', MEZ:'#9b51e0', OUT:'#f79009', MEC:'#667085' }
const seed = Array.from({ length: 30 }, (_, i) => ({ left:{ floor:floors[i%5], room:rooms[i%rooms.length], items:['Lights','Outlets'] }, right:{ floor:floors[(i+1)%5], room:rooms[(i+4)%rooms.length], items:['Lights','Dryer'] } }))

const usePanel = create((set) => ({ rows:seed, theme:'light', started:false, edit:null,
  set:(key,value)=>set({[key]:value}),
  save:(side,index,card)=>set(s=>({ rows:s.rows.map((r,i)=>i===index?{...r,[side]:card}:r), edit:null })),
  reset:()=>set({rows:seed})
}))

const Button = ({ children, variant='ghost', ...props }) => <button className={`button ${variant}`} {...props}>{children}</button>
function Label({ card, side, number, onClick }) { return <button className={`label ${side}`} onClick={onClick}><span className="label-main"><b>{card.room}</b><small>{card.floor}</small><span>{card.items.slice(0,3).join(' · ')}</span></span><i style={{background:dots[card.floor]}} /></button> }
function Dialog({ side,index,card }) { const save=usePanel(s=>s.save), close=usePanel(s=>s.set); const [draft,set]=useState(card)
  return <div className="scrim"><form className="dialog" onSubmit={e=>{e.preventDefault();save(side,index,{...draft,items:draft.items.filter(Boolean)})}}><header><div><span className="eyebrow">BREAKer {side==='left'?index*2+1:index*2+2}</span><h2>Edit label</h2></div><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button></header><label>Level<input list="floors" value={draft.floor} onChange={e=>set({...draft,floor:e.target.value})}/><datalist id="floors">{floors.map(x=><option key={x}/>)}</datalist></label><label>Room<input list="rooms" value={draft.room} onChange={e=>set({...draft,room:e.target.value})}/><datalist id="rooms">{rooms.map(x=><option key={x}/>)}</datalist></label><label>Fixtures <small>one per line</small><textarea value={draft.items.join('\n')} onChange={e=>set({...draft,items:e.target.value.split('\n')})}/></label><footer><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button><Button variant="primary">Save label</Button></footer></form></div> }
function Editor(){ const {rows,edit,set,reset}=usePanel(); return <main className="editor"><section className="settings"><div><span className="eyebrow">PROJECT SETTINGS</span><h2>60 breaker panel</h2><p>3.00 in labels · 0.75 in rows · dots face the breaker.</p></div><Button onClick={reset}>Reset samples</Button></section><section className="panel"><div className="rail"><h3>LEFT · ODD</h3>{rows.map((r,i)=><Label key={i} card={r.left} side="left" number={i*2+1} onClick={()=>set('edit',{side:'left',index:i,card:r.left})}/>)}</div><div className="numbers">{rows.map((_,i)=><span key={i}>{String(i*2+1).padStart(2,'0')} · {String(i*2+2).padStart(2,'0')}</span>)}</div><div className="rail"><h3>RIGHT · EVEN</h3>{rows.map((r,i)=><Label key={i} card={r.right} side="right" number={i*2+2} onClick={()=>set('edit',{side:'right',index:i,card:r.right})}/>)}</div></section>{edit&&<Dialog {...edit}/>}</main> }
function App(){ const {theme,set,started}=usePanel(); const root={className:theme}; const exportData=()=>{const raw=JSON.stringify(usePanel.getState().rows,null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.download='panel-labels.json';a.click()}
  return <div {...root}><header className="topbar"><a className="brand" href="#"><PanelTop/> Panel Labeler</a><nav><Button onClick={()=>set('theme',theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</Button><Button onClick={exportData}><Download/> Export</Button><Button onClick={()=>window.print()}><Printer/> Print / PDF</Button></nav></header>{started?<Editor/>:<main className="landing"><span className="pill"><Sparkles/> Free, printable, private by default</span><h1>Labels that make your panel<br/>feel <em>intentional.</em></h1><p>Design, edit, print, and share clean breaker labels. Your real circuit map stays in your browser.</p><div><Button variant="primary" onClick={()=>set('started',true)}>Open label maker</Button><Button onClick={()=>set('started',true)}><Settings2/> Explore sample panel</Button></div><aside><strong>Built for actual panels</strong><span>Editable rooms · custom fixtures · JSON backup · dark mode · print sizing</span></aside></main>}</div> }
export default App
