import { Bath, BedDouble, Download, Dumbbell, Fan, Hammer, Lightbulb, ListOrdered, Moon, PanelTop, Plug, Printer, Settings2, Sun, Trees, Waves, Wrench } from 'lucide-react'
import { useState } from 'react'
import { create } from 'zustand'
import { SmartInput } from './components/SmartInput'
import { IconPicker } from './components/IconPicker'

const rooms = ['Workshop','Laundry room','Kitchen','Bedroom','Bachelor','Bathroom','Office','Gym','Sauna','Staircase','Living room','Dining room','Garage','Terrace','Outside','Utility']
const floors = ['BSM','1ST','MEZ','OUT','MEC']
const dots = { BSM:'#3b82f6', '1ST':'#16a36a', MEZ:'#9b51e0', OUT:'#f79009', MEC:'#667085' }
const seed = Array.from({ length: 30 }, (_, i) => ({ left:{ floor:floors[i%5], room:rooms[i%rooms.length], items:['Lights','Outlets'], icon:'auto' }, right:{ floor:floors[(i+1)%5], room:rooms[(i+4)%rooms.length], items:['Lights','Dryer'], icon:'auto' } }))
seed[4].left.double=true;seed[5].left.reserved=true;seed[14].right.double=true;seed[15].right.reserved=true
const iconMap={Workshop:Hammer,Bedroom:BedDouble,Bachelor:BedDouble,Bathroom:Bath,Gym:Dumbbell,Sauna:Waves,Staircase:ListOrdered,Outside:Trees,Utility:Wrench}
const icons={auto:null,none:null,light:Lightbulb,plug:Plug,fan:Fan,hammer:Hammer,bed:BedDouble,bath:Bath,gym:Dumbbell,stairs:ListOrdered,trees:Trees,wrench:Wrench,waves:Waves}
const fixtureChoices=['Lights','Outlets','GFCI','Dryer','Washer','Baseboard heater','Floor heat','Ceiling fan','Oven','Dishwasher','Air exchange','Central vacuum','Water heater']
const autoFixture=(text='')=>/light|lamp/i.test(text)?'light':/outlet|plug|gfci/i.test(text)?'plug':/fan|air exchange/i.test(text)?'fan':null

const usePanel = create((set) => ({ rows:seed, theme:'light', started:false, edit:null, settingsOpen:false, config:{count:60,width:3,row:.75,printDots:true,language:'EN'},
  set:(key,value)=>set({[key]:value}),
  save:(side,index,card)=>set(s=>({ rows:s.rows.map((r,i)=>i===index?{...r,[side]:card}:i===index+1?{...r,[side]:{...r[side],reserved:!!card.double}}:r), edit:null })),
  reset:()=>set({rows:structuredClone(seed)})
}))

const Button = ({ children, variant='ghost', ...props }) => <button className={`button ${variant}`} {...props}>{children}</button>
function Label({ card, side, onClick }) { const Icon=card.icon&&card.icon!=='auto'?icons[card.icon]:iconMap[card.room]; const fixtures=(card.fixtures||card.items.map(text=>({text,icon:'auto'}))).filter(x=>x.text).slice(0,3); return <button style={card.double?{gridRow:'span 2'}:null} className={`label ${side} ${card.double?'double':''}`} onClick={onClick}><span className="label-main"><b>{Icon&&<Icon/>}{card.room}</b><small>{card.floor}</small><span>{fixtures.map((f,i)=>{const I=icons[f.icon==='auto'?autoFixture(f.text):f.icon];return <em key={i}>{I&&<I/>}{f.text}</em>})}</span></span><i style={{background:dots[card.floor]}} /></button> }
function Dialog({ side,index,card }) { const save=usePanel(s=>s.save), close=usePanel(s=>s.set); const [draft,set]=useState({...card,fixtures:card.fixtures||card.items.map(text=>({text,icon:'auto'}))}); const updateFixture=(i,part)=>set({...draft,fixtures:draft.fixtures.map((f,n)=>n===i?{...f,...part}:f)})
  return <div className="scrim"><form className="dialog" onSubmit={e=>{e.preventDefault();const fixtures=draft.fixtures.filter(f=>f.text);save(side,index,{...draft,fixtures,items:fixtures.map(f=>f.text)})}}><header><div><span className="eyebrow">BREAKER {side==='left'?index*2+1:index*2+2}</span><h2>Edit label</h2></div><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button></header><label>Level<SmartInput value={draft.floor} options={floors} onChange={floor=>set({...draft,floor})}/></label><div className="fields"><label>Room<SmartInput value={draft.room} options={rooms} onChange={room=>set({...draft,room})}/></label><label>Room icon<IconPicker value={draft.icon||'auto'} onChange={icon=>set({...draft,icon})}/></label></div><label>Fixtures</label><div className="fixture-rows">{[0,1,2,3].map(i=>{const f=draft.fixtures[i]||{text:'',icon:'auto'};const auto=autoFixture(f.text);return <div key={i}><SmartInput value={f.text} placeholder="Type or choose a fixture" options={fixtureChoices} onChange={text=>updateFixture(i,{text})}/><IconPicker value={f.icon} autoIcon={auto==='light'?'Lightbulb':auto==='plug'?'Plug':auto==='fan'?'Fan':undefined} onChange={icon=>updateFixture(i,{icon})}/></div>})}</div><label className="check"><input type="checkbox" checked={!!draft.double} onChange={e=>set({...draft,double:e.target.checked})}/> Double-height breaker — uses next position</label><footer><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button><Button variant="primary">Save label</Button></footer></form></div> }
function Editor(){ const {rows,edit,set,reset,config,settingsOpen}=usePanel(); const rowCount=config.count/2; const rail=(side)=><div className="rail"><h3>{side==='left'?'LEFT · ODD':'RIGHT · EVEN'}</h3>{rows.slice(0,rowCount).map((r,i)=>!r[side].reserved&&<Label key={i} card={r[side]} side={side} onClick={()=>set('edit',{side,index:i,card:r[side]})}/>)}</div>; return <main className="editor"><section className="settings"><div><span className="eyebrow">PROJECT SETTINGS</span><h2>{config.count} breaker panel</h2><p>Click a label to edit its room, icon, fixtures, or double-height span.</p></div><div><Button onClick={()=>set('settingsOpen',!settingsOpen)}><Settings2/> Settings</Button><Button onClick={reset}>Reset samples</Button></div></section>{settingsOpen&&<section className="settings-card"><label>Breaker count<input type="number" min="2" max="60" step="2" value={config.count} onChange={e=>set('config',{...config,count:+e.target.value})}/></label><label>Label width (in)<input type="number" step=".25" value={config.width} onChange={e=>set('config',{...config,width:+e.target.value})}/></label><label>Row height (in)<input type="number" step=".05" value={config.row} onChange={e=>set('config',{...config,row:+e.target.value})}/></label><label>Print color dots<input type="checkbox" checked={config.printDots} onChange={e=>set('config',{...config,printDots:e.target.checked})}/></label></section>}<section className={`panel ${config.printDots?'':'no-dots'}`} style={{'--row-h':`${config.row}in`,'--label-w':`${config.width}in`}}>{rail('left')}<div className="numbers">{rows.slice(0,rowCount).map((_,i)=><span key={i}>{String(i*2+1).padStart(2,'0')} · {String(i*2+2).padStart(2,'0')}</span>)}</div>{rail('right')}</section>{edit&&<Dialog {...edit}/>}</main> }
function App(){ const {theme,set}=usePanel(); const exportData=()=>{const raw=JSON.stringify(usePanel.getState().rows,null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.download='panel-labels.json';a.click()};return <div className={theme}><header className="topbar"><a className="brand" href="#"><PanelTop/> Panel Labeler</a><nav><Button onClick={()=>set('theme',theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</Button><Button onClick={exportData}><Download/> Export</Button><Button onClick={()=>window.print()}><Printer/> Print / PDF</Button></nav></header><Editor/></div> }
export default App
