import { Bath, BedDouble, Download, Dumbbell, Fan, Hammer, Lightbulb, ListOrdered, Moon, PanelTop, Plug, Printer, Sun, Trees, Waves, Wrench } from 'lucide-react'
import { useState } from 'react'
import { create } from 'zustand'

const rooms = ['Workshop','Laundry room','Kitchen','Bedroom','Bachelor','Bathroom','Office','Gym','Sauna','Staircase','Living room','Dining room','Garage','Terrace','Outside','Utility']
const floors = ['BSM','1ST','MEZ','OUT','MEC']
const dots = { BSM:'#3b82f6', '1ST':'#16a36a', MEZ:'#9b51e0', OUT:'#f79009', MEC:'#667085' }
const seed = Array.from({ length: 30 }, (_, i) => ({ left:{ floor:floors[i%5], room:rooms[i%rooms.length], items:['Lights','Outlets'], icon:'auto' }, right:{ floor:floors[(i+1)%5], room:rooms[(i+4)%rooms.length], items:['Lights','Dryer'], icon:'auto' } }))
seed[4].left.double=true;seed[5].left.reserved=true;seed[14].right.double=true;seed[15].right.reserved=true
const iconMap={Workshop:Hammer,Bedroom:BedDouble,Bachelor:BedDouble,Bathroom:Bath,Gym:Dumbbell,Sauna:Waves,Staircase:ListOrdered,Outside:Trees,Utility:Wrench}
const icons={auto:null,none:null,light:Lightbulb,plug:Plug,fan:Fan,hammer:Hammer,bed:BedDouble,bath:Bath,gym:Dumbbell,stairs:ListOrdered,trees:Trees,wrench:Wrench,waves:Waves}

const usePanel = create((set) => ({ rows:seed, theme:'light', started:false, edit:null,
  set:(key,value)=>set({[key]:value}),
  save:(side,index,card)=>set(s=>({ rows:s.rows.map((r,i)=>i===index?{...r,[side]:card}:i===index+1?{...r,[side]:{...r[side],reserved:!!card.double}}:r), edit:null })),
  reset:()=>set({rows:seed})
}))

const Button = ({ children, variant='ghost', ...props }) => <button className={`button ${variant}`} {...props}>{children}</button>
function Label({ card, side, onClick }) { const Icon=card.icon&&card.icon!=='auto'?icons[card.icon]:iconMap[card.room]; return <button style={card.double?{gridRow:'span 2'}:null} className={`label ${side} ${card.double?'double':''}`} onClick={onClick}><span className="label-main"><b>{Icon&&<Icon/>}{card.room}</b><small>{card.floor}</small><span>{card.items.slice(0,3).join(' · ')}</span></span><i style={{background:dots[card.floor]}} /></button> }
function Dialog({ side,index,card }) { const save=usePanel(s=>s.save), close=usePanel(s=>s.set); const [draft,set]=useState(card)
  return <div className="scrim"><form className="dialog" onSubmit={e=>{e.preventDefault();save(side,index,{...draft,items:draft.items.filter(Boolean)})}}><header><div><span className="eyebrow">BREAKER {side==='left'?index*2+1:index*2+2}</span><h2>Edit label</h2></div><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button></header><div className="fields"><label>Level<input list="floors" value={draft.floor} onChange={e=>set({...draft,floor:e.target.value})}/><datalist id="floors">{floors.map(x=><option key={x}/>)}</datalist></label><label>Room<input list="rooms" value={draft.room} onChange={e=>set({...draft,room:e.target.value})}/><datalist id="rooms">{rooms.map(x=><option key={x}/>)}</datalist></label><label>Room icon<select value={draft.icon||'auto'} onChange={e=>set({...draft,icon:e.target.value})}>{Object.keys(icons).map(x=><option key={x} value={x}>{x}</option>)}</select></label></div><label>Fixtures <small>one per line</small><textarea value={draft.items.join('\n')} onChange={e=>set({...draft,items:e.target.value.split('\n')})}/></label><label className="check"><input type="checkbox" checked={!!draft.double} onChange={e=>set({...draft,double:e.target.checked})}/> Double-height breaker — uses next position</label><footer><Button type="button" onClick={()=>close('edit',null)}>Cancel</Button><Button variant="primary">Save label</Button></footer></form></div> }
function Editor(){ const {rows,edit,set,reset}=usePanel(); const rail=(side)=><div className="rail"><h3>{side==='left'?'LEFT · ODD':'RIGHT · EVEN'}</h3>{rows.map((r,i)=>!r[side].reserved&&<Label key={i} card={r[side]} side={side} onClick={()=>set('edit',{side,index:i,card:r[side]})}/>)}</div>; return <main className="editor"><section className="settings"><div><span className="eyebrow">PROJECT SETTINGS</span><h2>60 breaker panel</h2><p>Click a label to edit its room, icon, fixtures, or double-height span.</p></div><Button onClick={reset}>Reset samples</Button></section><section className="panel">{rail('left')}<div className="numbers">{rows.map((_,i)=><span key={i}>{String(i*2+1).padStart(2,'0')} · {String(i*2+2).padStart(2,'0')}</span>)}</div>{rail('right')}</section>{edit&&<Dialog {...edit}/>}</main> }
function App(){ const {theme,set}=usePanel(); const exportData=()=>{const raw=JSON.stringify(usePanel.getState().rows,null,2),a=document.createElement('a');a.href=URL.createObjectURL(new Blob([raw],{type:'application/json'}));a.download='panel-labels.json';a.click()};return <div className={theme}><header className="topbar"><a className="brand" href="#"><PanelTop/> Panel Labeler</a><nav><Button onClick={()=>set('theme',theme==='light'?'dark':'light')}>{theme==='light'?<Moon/>:<Sun/>}</Button><Button onClick={exportData}><Download/> Export</Button><Button onClick={()=>window.print()}><Printer/> Print / PDF</Button></nav></header><Editor/></div> }
export default App
